parserOptions:
  ecmaFeatures:
    impliedStrict: true
  ecmaVersion: 2017
  sourceType: module

rules:
  indent:
    - error
    - 4
    -
      SwitchCase: 1
  no-var:
    - error
  prefer-const:
    - error
  semi:
    - error
    - never